[[constraint]]
  name = "github.com/msales/pkg"
  version = "^1.7.0"

[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.*"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.*"

[[constraint]]
  name = "github.com/segmentio/ksuid"
  version = "1.*"

[[constraint]]
  name = "github.com/go-zoo/bone"
  version = "1.*"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.*"

[[constraint]]
  name = "gopkg.in/inconshreveable/log15.v2"
  version = "2.11.*"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.*"

[prune]
  go-tests = true
